export const ORDER_CREATE_REQUEST = "ORDER_CREATE_REQUEST";
export const ORDER_CREATE_SUCCESS = "ORDER_CREATE_SUCCESS";
export const ORDER_CREATE_FAIL = "ORDER_CREATE_FAIL";

export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAIL = "ORDER_LIST_FAIL";

export const ORDER_DATA_REQUEST = "ORDER_DATA_REQUEST";
export const ORDER_DATA_SUCCESS = "ORDER_DATA_SUCCESS";
export const ORDER_DATA_FAIL = "ORDER_DATA_FAIL";

export const ORDER_SALE_DATA_REQUEST = "ORDER_SALE_DATA_REQUEST";
export const ORDER_SALE_DATA_SUCCESS = "ORDER_SALE_DATA_SUCCESS";
export const ORDER_SALE_DATA_FAIL = "ORDER_SALE_DATA_FAIL";


